#!/bin/sh
if command -v brew >/dev/null 2>&1; then
	echo "› Homebrew is already installed"
else
	echo "› Homebrew not found, installing now..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "› Installing software defined by Brewfile"
brew bundle --file "$DOTFILES/software/Brewfile"